# Generated by Django 5.0.6 on 2024-06-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answers",
            field=models.TextField(default="1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="correct_option",
            field=models.IntegerField(default="1"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[("easy", "EASY"), ("medium", "MEDIUM"), ("heard", "HARD")],
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
    ]
